/**
 * BitePerk contact-form backend.
 *
 * Reached same-origin as POST /api/contact via a Firebase Hosting rewrite
 * (see firebase.json). Flow: validate → write lead to the named Firestore
 * database `biteperk-leads` (the source of truth) → best-effort Zoho SMTP
 * notification → respond. A failed email never fails the request; the saved
 * lead is what matters.
 *
 * Named-DB binding (getFirestore(databaseId)) requires firebase-admin >= 12.
 */
const { onRequest } = require("firebase-functions/v2/https");
const { defineSecret } = require("firebase-functions/params");
const logger = require("firebase-functions/logger");
const { initializeApp } = require("firebase-admin/app");
const { getFirestore, FieldValue } = require("firebase-admin/firestore");
const nodemailer = require("nodemailer");

initializeApp();
const db = getFirestore("biteperk-leads"); // named DB in australia-southeast1

const ZOHO_SMTP_PASS = defineSecret("ZOHO_SMTP_PASS");
const RECAPTCHA_SECRET_KEY = defineSecret("RECAPTCHA_SECRET_KEY");
const RECAPTCHA_VERIFY_URL = "https://www.google.com/recaptcha/api/siteverify";
const RECAPTCHA_TOKEN_MAX_LENGTH = 16384;

// --- Non-secret config (hardcoded on purpose; only the password is a secret) ---
// Auth as the real mailbox (biteperk@); hello@ is an alias of it. We send From
// the hello@ alias, but Zoho only permits that if the alias's send-as is set up
// — so sendNotification falls back to From the mailbox if the alias is rejected.
const SMTP = { host: "smtp.zoho.com.au", port: 465, secure: true, user: "biteperk@biteperk.com.au" };
const MAIL_FROM = '"Biteperk" <hello@biteperk.com.au>';
const MAIL_FROM_FALLBACK = '"Biteperk" <biteperk@biteperk.com.au>';
const MAIL_TO = "hello@biteperk.com.au";
const MAIL_CC = "biteperk@gmail.com"; // backstop copy
const SITE_URL = "https://biteperk.com/au-en";
const ZOHO_WEB_TO_LEAD_URL = "https://crm.zoho.com.au/crm/WebToLeadForm";
// Public identifiers generated by Zoho's Web-to-Lead form builder. They are
// intended to ship in browser embeds; we submit them server-side instead so
// the BitePerk form, CSP, validation and first-party lead backup stay intact.
const ZOHO_WEB_TO_LEAD = {
  xnQsjsdp: "106d6622afb9206c36fc7aa548b8105650576951a1076dc8962118e766435f3c",
  xmIwtLD: "589312d26c0939d08474f6f254ce20d14db5d544ccf1f8c7a402d8905830d54d13a4b24cae0075f31761c2cde6ab39f4",
  actionType: "TGVhZHM=",
};
// AU site + the international .com hub (EU/UK/US are served from /en/ and /fr/
// on biteperk.com). Both functions stay in australia-southeast1; only the
// browser Origin allowlist widens so the EU contact form isn't blocked by CORS.
// (International architecture: PLAN.md §7 — "Functions deploy before hosting".)
const ALLOWED_ORIGINS = [
  "https://biteperk.com.au",
  "https://www.biteperk.com.au",
  "https://biteperk.com",
  "https://www.biteperk.com",
];

// Keep in sync with src/data/products.ts (the function can't import the site's TS).
// Legacy voco*/perk* slugs stay accepted during the Vox rename transition —
// cached pages and old outbound links may still post them.
const PRODUCT_SLUGS = new Set([
  "voxtable", "voxorder", "voxconcierge", "voxdrive",
  "voxstay",
  "vocotable", "vocoorder", "vococoncierge", "vocodrive",
  "perktable", "perkorder", "perkconcierge", "perkdrive",
  "general", "",
]);

const str = (v, max) => (typeof v === "string" ? v : "").trim().slice(0, max); // coerce + cap
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

exports.contactForm = onRequest(
  {
    region: "australia-southeast1",
    secrets: [ZOHO_SMTP_PASS, RECAPTCHA_SECRET_KEY],
    cors: false,
    maxInstances: 5,
    timeoutSeconds: 30,
    memory: "256MiB",
  },
  async (req, res) => {
    if (req.method === "OPTIONS") return res.status(204).send("");
    if (req.method !== "POST") {
      res.set("Allow", "POST");
      return finish(res, false, 405, "Method not allowed", false);
    }

    // Same-origin only. Browsers always send Origin on cross-site POSTs;
    // curl / native no-JS submits may omit it, which we allow.
    const origin = req.get("origin");
    if (origin && !ALLOWED_ORIGINS.includes(origin)) {
      return finish(res, false, 403, "Forbidden", false);
    }

    const wantsJson = (req.get("accept") || "").includes("application/json");
    const b = req.body && typeof req.body === "object" ? req.body : {};

    // Honeypot: bots fill it, humans don't. Fake success, write nothing.
    if (str(b._gotcha, 100)) return finish(res, true, 200, null, wantsJson);

    const name = str(b.name, 200);
    const email = str(b.email, 320);
    const message = str(b.message, 5000);
    const venue = str(b.venue, 200);
    let product = str(b.product, 60);
    if (!PRODUCT_SLUGS.has(product)) product = "";

    // First-touch campaign attribution (JSON string from the form's hidden
    // field). Stored verbatim (capped) so we can see which campaign drove
    // each lead; never parsed/executed, purely a record on the enquiry.
    const attribution = str(b.attribution, 1000);
    const crmForm = str(b.crmForm, 40);

    const zohoGlobal = crmForm === "zoho-global";
    if (
      !name ||
      !EMAIL_RE.test(email) ||
      !message ||
      (zohoGlobal && (!venue || !ZOHO_PRODUCT_LABELS[product]))
    ) {
      const error = zohoGlobal
        ? "Please add your name, venue, product, a valid email, and a message."
        : "Please add your name, a valid email, and a message.";
      return finish(res, false, 400, error, wantsJson);
    }

    // The checkbox is only a token generator. The /en CRM form is not
    // accepted until Google verifies that token here on the server.
    if (zohoGlobal) {
      // reCAPTCHA response sizes are not fixed and can exceed 2 KiB. Reject an
      // unreasonable payload instead of truncating its cryptographic signature.
      const recaptchaToken = typeof b["g-recaptcha-response"] === "string"
        ? b["g-recaptcha-response"].trim()
        : "";
      if (recaptchaToken.length > RECAPTCHA_TOKEN_MAX_LENGTH) {
        logger.warn("contactForm: oversized reCAPTCHA token", { tokenLength: recaptchaToken.length });
        return finish(res, false, 403, "Please complete the human verification and try again.", wantsJson);
      }
      const remoteIp = str((req.get("x-forwarded-for") || "").split(",")[0], 60);
      const verified = await verifyRecaptcha(recaptchaToken, remoteIp);
      if (!verified) {
        return finish(
          res,
          false,
          403,
          "Please complete the human verification and try again.",
          wantsJson,
        );
      }
    }

    let docId;
    try {
      const ref = await db.collection("contactSubmissions").add({
        name,
        email,
        venue: venue || null,
        product: product || null,
        message,
        attribution: attribution || null,
        crmForm: crmForm || null,
        createdAt: FieldValue.serverTimestamp(),
        userAgent: str(req.get("user-agent"), 500) || null,
        ip: str((req.get("x-forwarded-for") || "").split(",")[0], 60) || null,
      });
      docId = ref.id;
    } catch (e) {
      logger.error("contactForm: Firestore write failed", { msg: e.message });
      return finish(res, false, 500, "Sorry — something went wrong. Please email hello@biteperk.com.au.", wantsJson);
    }

    // The international /en form is connected to Zoho CRM. Firestore remains
    // the source of truth, so a temporary Zoho outage never loses the enquiry
    // or tells the visitor their already-saved message failed.
    if (zohoGlobal) {
      try {
        await submitZohoLead({ name, email, venue, product, message });
      } catch (e) {
        logger.error("contactForm: Zoho CRM lead failed (lead is saved)", { docId, msg: e.message });
      }
    }

    // Best-effort notification. Never fail the request on email trouble.
    try {
      await sendNotification({ name, email, venue, product, message, docId });
    } catch (e) {
      logger.error("contactForm: email failed (best-effort, lead is saved)", { docId, msg: e.message });
    }

    return finish(res, true, 200, null, wantsJson);
  }
);

const ZOHO_PRODUCT_LABELS = {
  voxtable: "VoxTable",
  voxorder: "VoxOrder",
  voxconcierge: "VoxConcierge",
  voxdrive: "VoxDrive",
  voxstay: "VoxStay",
};

async function verifyRecaptcha(token, remoteIp) {
  if (!token) return false;

  try {
    const secret = RECAPTCHA_SECRET_KEY.value();
    const body = new URLSearchParams({
      secret,
      response: token,
    });
    if (remoteIp) body.set("remoteip", remoteIp);

    const response = await fetch(RECAPTCHA_VERIFY_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body,
      signal: AbortSignal.timeout(7000),
    });
    if (!response.ok) {
      logger.warn("contactForm: reCAPTCHA Siteverify HTTP failure", { status: response.status });
      return false;
    }

    const result = await response.json();
    if (!result.success) {
      logger.warn("contactForm: reCAPTCHA rejected token", {
        errors: result["error-codes"] || [],
        tokenLength: token.length,
      });
      return false;
    }

    // Domain validation is also configured on the reCAPTCHA key. Checking the
    // returned hostname here provides a second server-side boundary.
    return ["biteperk.com", "www.biteperk.com"].includes(result.hostname);
  } catch (e) {
    logger.warn("contactForm: reCAPTCHA verification failed", { msg: e.message });
    return false;
  }
}

/** Submit the validated global enquiry to Zoho CRM's Web-to-Lead endpoint. */
async function submitZohoLead({ name, email, venue, product, message }) {
  const body = new URLSearchParams({
    xnQsjsdp: ZOHO_WEB_TO_LEAD.xnQsjsdp,
    zc_gad: "",
    xmIwtLD: ZOHO_WEB_TO_LEAD.xmIwtLD,
    actionType: ZOHO_WEB_TO_LEAD.actionType,
    returnURL: "null",
    "Last Name": name,
    Company: venue,
    Email: email,
    LEADCF1: ZOHO_PRODUCT_LABELS[product] || "VoxTable",
    Description: message,
    "Lead Source": "Online Store",
    aG9uZXlwb3Q: "",
  });

  const response = await fetch(ZOHO_WEB_TO_LEAD_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8" },
    body,
    redirect: "manual",
    signal: AbortSignal.timeout(8000),
  });

  if (response.status < 200 || response.status >= 400) {
    throw new Error(`Zoho Web-to-Lead returned HTTP ${response.status}`);
  }
}

/** Send the lead notification via Zoho SMTP with tight timeouts so a broken
 *  mail server can never stall the (already-saved) request for long. */
async function sendNotification({ name, email, venue, product, message, docId }) {
  const transporter = nodemailer.createTransport({
    host: SMTP.host,
    port: SMTP.port,
    secure: SMTP.secure,
    auth: { user: SMTP.user, pass: ZOHO_SMTP_PASS.value() },
    connectionTimeout: 5000,
    greetingTimeout: 5000,
    socketTimeout: 8000,
  });

  const subject = `New website enquiry — ${name}${product ? ` · ${product}` : ""}`;
  const text = [
    `New enquiry from the BitePerk website.`,
    ``,
    `Name:    ${name}`,
    `Email:   ${email}`,
    `Venue:   ${venue || "—"}`,
    `About:   ${product || "—"}`,
    ``,
    `Message:`,
    message,
    ``,
    `— Reply directly to this email to respond to ${name}.`,
    `(ref: ${docId})`,
  ].join("\n");

  const msg = { to: MAIL_TO, cc: MAIL_CC, replyTo: email, subject, text };

  try {
    await transporter.sendMail({ ...msg, from: MAIL_FROM }); // From the hello@ alias
  } catch (e) {
    // Zoho rejects send-as if the hello@ alias isn't set up for this mailbox.
    // Retry From the authenticated mailbox so the lead notification still lands.
    logger.warn("contactForm: alias From rejected, retrying from mailbox", { docId, msg: e.message });
    await transporter.sendMail({ ...msg, from: MAIL_FROM_FALLBACK });
  }
}

/** JSON for the fetch() path; branded full-page HTML only for the no-JS native submit. */
function finish(res, ok, status, error, wantsJson) {
  if (wantsJson) {
    return res.status(ok ? 200 : status).json(ok ? { ok: true } : { ok: false, error });
  }
  res.set("Content-Type", "text/html; charset=utf-8");
  return res.status(ok ? 200 : status).send(ok ? thankYouHtml() : errorHtml(error));
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => (
    { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
  ));
}

function page(title, heading, body) {
  // Self-contained, inline styles only (no inline <script>) so it stays clean
  // under the site CSP. Reached only when JavaScript is disabled.
  return `<!doctype html>
<html lang="en-AU">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex" />
<title>${escapeHtml(title)} · BitePerk</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; min-height: 100vh; display: grid; place-items: center;
    background: #0A0B0D; color: #E7EAEE;
    font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    padding: 24px;
  }
  .card {
    max-width: 520px; width: 100%; text-align: center;
    padding: 40px 32px; border: 1px solid rgba(255,255,255,0.08);
    border-radius: 20px; background: #121317;
    box-shadow: 0 30px 80px -30px rgba(0,0,0,0.7);
  }
  .brand { font-weight: 800; letter-spacing: -0.02em; font-size: 20px; margin-bottom: 24px; }
  .brand span { color: #F5C418; }
  h1 { font-size: clamp(24px, 4vw, 32px); margin: 0 0 12px; letter-spacing: -0.02em; color: #fff; }
  p { margin: 0 0 24px; color: #9AA3AD; line-height: 1.6; }
  a.btn {
    display: inline-block; text-decoration: none; font-weight: 700;
    background: #F5C418; color: #0A0B0D; padding: 13px 22px; border-radius: 999px;
  }
</style>
</head>
<body>
  <main class="card">
    <div class="brand">bite<span>perk</span></div>
    <h1>${escapeHtml(heading)}</h1>
    <p>${body}</p>
    <a class="btn" href="${SITE_URL}/">Back to biteperk.com.au →</a>
  </main>
</body>
</html>`;
}

function thankYouHtml() {
  return page(
    "Message sent",
    "Thanks — we'll be in touch.",
    "Your message has reached the BitePerk team. We usually reply within a few hours during business hours (Mon–Fri, 9am–5pm AEST)."
  );
}

function errorHtml(error) {
  return page(
    "Something went wrong",
    "That didn't go through.",
    `${escapeHtml(error || "Please try again.")} You can also email us directly at <a style="color:#F5C418" href="mailto:hello@biteperk.com.au">hello@biteperk.com.au</a>.`
  );
}

/**
 * Privacy-friendly analytics proxy (Plausible).
 *
 * Reached same-origin as POST /api/event via a Firebase Hosting rewrite —
 * keeps the CSP at connect-src 'self' with no third-party request from the
 * browser. Forwards the raw event body plus the visitor's UA and client IP
 * (both required by Plausible for correct unique-visitor counting; neither
 * is stored by us). Fire-and-forget: analytics must never break the site,
 * so every failure path still returns 202.
 *
 * Inert until the Plausible site (biteperk.com.au) exists AND the client
 * flag in src/scripts/analytics.ts is flipped to true.
 */
exports.analyticsEvent = onRequest(
  {
    region: "australia-southeast1",
    cors: false,
    maxInstances: 3,
    timeoutSeconds: 10,
    memory: "128MiB",
  },
  async (req, res) => {
    if (req.method !== "POST") {
      res.set("Allow", "POST");
      return res.status(405).end();
    }
    const origin = req.get("origin");
    if (origin && !ALLOWED_ORIGINS.includes(origin)) return res.status(403).end();
    try {
      await fetch("https://plausible.io/api/event", {
        method: "POST",
        headers: {
          "Content-Type": req.get("content-type") || "application/json",
          "User-Agent": req.get("user-agent") || "",
          "X-Forwarded-For": (req.get("x-forwarded-for") || "").split(",")[0].trim(),
        },
        body: req.rawBody,
      });
    } catch (e) {
      logger.warn("analytics forward failed", e);
    }
    return res.status(202).end();
  }
);
