#!/usr/bin/env node
/**
 * llms.txt gate — the AI-crawler manifest names the pages that exist, on the
 * canonical host. Until 13 Sep 2026 the shipped file pointed ~40 URLs at the
 * redirect-only biteperk.com.au and had no Solutions or Resources section.
 *
 * Asserts over dist/llms.txt (generated by scripts/build/llms-au.mjs):
 *   - no https://biteperk.com.au URL (the mailbox is not a URL)
 *   - every product, live solution, published city, resources hub and
 *     populated category URL appears byte-exact
 *   - every https://biteperk.com/au-en/… URL resolves to a built page
 * And over dist-site/llms.txt when present: the international section and
 * every global section header (merge-dist composition).
 */
import { existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadTS } from "../build/_load-ts.mjs";
import { populatedResourceTypes } from "../build/content-index.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const FILE = process.env.LLMS_FILE ?? join(ROOT, "dist/llms.txt");
if (!existsSync(FILE)) { console.error(`check-llms: ${FILE} not found — run npm run build.`); process.exit(1); }
const txt = readFileSync(FILE, "utf8");

const { AU_HOME } = await loadTS(join(ROOT, "src/data/locales.ts"));
const { PRODUCT_SLUGS } = await loadTS(join(ROOT, "src/data/product-slugs.ts"));
const { liveSolutions } = await loadTS(join(ROOT, "src/data/solutions.ts"));
const { publishedCities } = await loadTS(join(ROOT, "src/data/cities.ts"));
const { resourceTypes } = await loadTS(join(ROOT, "src/data/resources.ts"));
const populated = populatedResourceTypes();

let failed = 0;
const fail = (m) => { failed++; console.error(`FAIL  ${m}`); };

if (/https:\/\/biteperk\.com\.au\b/.test(txt)) fail("llms.txt names https://biteperk.com.au — the redirect-only host");
const must = [
  ...PRODUCT_SLUGS.map((s) => `${AU_HOME}/products/${s}/`),
  ...liveSolutions().map((s) => `${AU_HOME}/solutions/${s.slug}/`),
  ...publishedCities.map((c) => `${AU_HOME}/${c.slug}/`),
  `${AU_HOME}/resources/`,
  ...resourceTypes.filter((t) => populated.has(t.id)).map((t) => `${AU_HOME}${t.path}`),
];
for (const u of must) if (!txt.includes(u)) fail(`llms.txt does not list ${u}`);
const DIST = join(ROOT, "dist");
for (const m of txt.matchAll(new RegExp(`${AU_HOME.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(/[^)\\s"']*)`, "g"))) {
  const path = m[1].replace(/[),.]+$/, "");
  const file = /\.[a-z0-9]+$/i.test(path) ? join(DIST, path) : join(DIST, path.replace(/\/$/, ""), "index.html");
  if (!existsSync(file)) fail(`llms.txt names ${AU_HOME}${path}, which is not built`);
}
const SITE = join(ROOT, "dist-site/llms.txt");
if (existsSync(SITE)) {
  const root = readFileSync(SITE, "utf8");
  for (const h of ["## International sites", "## Capabilities", "## Product facts", "## Notes for answer engines"]) {
    if (!root.includes(h)) fail(`dist-site/llms.txt lacks the "${h}" section (merge-dist composition)`);
  }
}
if (failed) { console.error(`\ncheck-llms: ${failed} failure(s)`); process.exit(1); }
console.log(`check-llms: ok — ${must.length} registry URLs listed on the canonical host; every named page is built`);
